### ISSUE TITLE
CSS styling issues in the AboutUs page.

### ISSUE THREAD

**Issue by Kingsleyyong** [Kingsleyyong/IWP-Project#3]
The issues are on Game Page, about us page and profile page.
Conflict from lyn's CSS file with Matt's BootStrap file.

**Comment by mattlab7** [comment]
@Kingsleyyong @LynChee1229 
What kind of behaviour does it exhibit?
How is it supposed to look like?

![image](https://user-images.githubusercontent.com/43501106/107867637-8981fc80-6eb7-11eb-81ed-217193e86f27.png)
![image](https://user-images.githubusercontent.com/43501106/107867785-af5bd100-6eb8-11eb-89fe-e2625ab1f97f.png)
![image](https://user-images.githubusercontent.com/43501106/107867804-da462500-6eb8-11eb-8439-ce2aa7a5b6c8.png)

**Comment by Kingsleyyong** [comment]
You see the about us part, u try to comment the header part and see.

**Comment by mattlab7** [comment]
I see, how about I restyle these pages, to make it consistent?

**Comment by Kingsleyyong** [comment]
For me ahould be okay, u can ask lyn bc those page previously had design are from lyn.

**Comment by mattlab7** [comment]
Alright, you okay with it Lyn? 
@LynChee1229

**Comment by mattlab7** [comment]
fixed with [https://github.com/Kingsleyyong/IWP-Project/commit/7b02dec8d66b3754d26132bd661e2cd3fa6a565c](7b02dec8d66b3754d26132bd661e2cd3fa6a565c)
