### ISSUE TITLE
Navbar Profile Dropdown 

### ISSUE THREAD

**Issue by Kingsleyyong** [Kingsleyyong/IWP-Project#6]
I just created a dropdown menu on the profile logo by referring to the youtube tutorial.
There have some issues that need @mattlab7 your help to solve since I'm not familiar with Bootstrap.

**Comment by mattlab7** [comment]
Do you need this immediately? I plan to make styles for the pages with no styles first, then I focus on fixing, if you need this immediately tell me ya

**Comment by mattlab7** [comment]
On the other note, do you need any other thing to fix in the navbar or footer?

**Comment by Kingsleyyong** [comment]
okay, take your steps. Because actually some of the pages I still need your UI first only can do for my logic part because I'm not so sure about BootStrap 🥺. I think is just the navbar hamburger issues and this profile drop down.

**Comment by mattlab7** [comment]
Yeah I think both of them is technically the same type of problem, ETA tonight

**Comment by mattlab7** [comment]
![msedge_5FDqOfuXUH](https://user-images.githubusercontent.com/43501106/109373946-d79df380-78ec-11eb-81d9-07614928723d.png)
done
